= Spew

Spew provides code for use by clients interacting with service providers such as Flickr, Google Photos and Twitter. Currently OAuth1 and OAuth2 over REST is supported.

There is also code for managing photos hosted by service providers which also have a local copy.

=== Should you use it?

Probably not. This code is experimental and subject to radical change at no notice. It's being used and maintained by a single developer and is not ready for sharing.

The OAuth client implementation is hand-rolled. That will probably change so that the OAuth client implementation is pluggable, allowing Spring Social or Google OAuth Client to be used instead of the hand-rolled OAuth code.

If you're having trouble connecting to one of the services which Spew interacts with, looking at the code here might be helpful. TODO! more pointers.

=== Why Spew?

Spew stands for Service Provider Easy Win.

When thinking of words beginning with "sp", "spew" jumped to mind, and Easy Win was extrapolated from that.

=== History

This project started with a hand-rolled OAuth client to help manage photographs hosted on Flickr.

The decision to hand-roll to OAuth client was an exercise to help the developer understand the nuances of OAuth.

The code evolved as experiments were made with other service providers, mostly for hosting photographs elsewhere, with a foray into getting metrics from Twitter.
