= TODO

My TODO list. In no particular order. Some of these may never happen.

* LocalLibrary and a mechanism to find the original local copy of a photo found on Flickr, Google Photos etc.
Finding the local copy will be based on the DateTaken if it is available. Perhaps put local file name into a tag on the photo.

* Handle 401 failures, and reauthorize (just once).

* Handle 5xx failures with wait and retry (repeated retries with increasing waits, see Google API doc)

* tags for "uncertain" and "doubtful" (or similar) to correspond to "?" and "??" in titles

* Connection impl for unit tests which returns responses from resource files

* Connection impl using Spring Social for OAuth2 (currently only OAuth1 supported)

* Make auth requests using Spring Social (currently only works if key and secret are already in store)

* Connection impl using Google OAuth client lib.

* Integration tests. These would be useful to me locally but could not be run from a build server because they require
application keys and secrets which must not be committed. Probably use in memory store for user keys and secrets,
so that integration tests do auth.

* Build static website from local photos with appropriate tags/ratings. Probably need to build thumbnails (ImageMagick?).
Lots of options for website: template or from scratch? Will want JavaScript. Hosting would need sorted too.

* Processor to check that photos timestamps match the folder they are in.
Perhaps automatically correct problems, could use this to move files from memory cards?

* Extract messages from error responses.

* Revisit date handling for most service providers. Consider use of java.time.Clock.

* Add ability to write to sidecar files.

* [depends on previous] processor to synchronise descriptions (and perhaps other metadata).
Many useful descriptions have been written on Flickr, which should be written back to the sidecar.
If it's not clear which description is newer, then a problem should be reported and resolved manually.

* Allow open ended date ranges.

* New ImageIterator which wraps PathIterator but returns only single element for raw+jpg+sidecar, raw+sidecar, raw+jpg, raw+jpg1+jpg2 etc.

* SPI for "is file content binary" and "is file content camera raw"

* Add support for basic auth (and digest auth?)
https://en.wikipedia.org/wiki/Basic_access_authentication
https://en.wikipedia.org/wiki/Digest_access_authentication
Github supports modified basic auth (returns 404 rather than 401 for failed auth)
https://developer.github.com/v3/auth/

* Remove references to SpewApplication and SpewServiceProvider from SpewConnection implementations.
Ideally the connection layer would have no knowledge of the application layer.

* More work required to prevent JsonConfiguration being passed around too much.

* Could first obtain authorization when opening the connection rather than checking when sending every request

* State/nonce usage incomplete in Boa implementations.

* Static methods on CallbackServer which cause it to start and stop?
Perhaps register(key, requestHandlers) and deregister(key).
Order of request handlers if multiple register() calls?
Equality of request handlers in case already registered?

* Show 500 page when there's a server-side error.
Perhaps show stacktrace. Maybe conditionally.

* Flickr "?perms=write" should be added in the application, with the path in the service provider

* Twitter OAuth2 and OAuth1
Needs OAuth1 to support grant_type=client_credentials

* Keep snapshot of Twitter followers.
And add abilty to update large followers list over a long period.
This call is capped at 15 requests per 15 minutes and 200 users per request.

* Add more service providers
 ** Evernote https://dev.evernote.com/doc/
 
 * Add more OAuth clients https://oauth.net/code/java/
 
 * Bin HardCodedTagLoader
 
 * Support video on Flickr. Tag and title tidy etc to work with video too.

 * Remove @SpewAuthType

 * Album descriptions and common album code (currently in FlickrPhotoUpdateProcessor)

 * Allow scope to be specified on ApplicationRequest,
   and re-authorise if scope associated with the connection does not include the additional scope on the request.
 
